-- CreateTable
CREATE TABLE "QueryView" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "filterName" TEXT NOT NULL,
    "filters" TEXT NOT NULL,
    "userName" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
